### ISSUE TITLE
UX Add alt info to icons

### ISSUE THREAD

**Issue by 2075** [cookiengineer/stealth-browser#24]
User wants to understand functionality of buttons without reading a manual.

Rollover could trigger display of an alt info or info in the status bar.

**Comment by cookiengineer** [comment]
You can try pressing 3 times `[ESC]` to see the shortcut usage ;)

Though I agree that this could be better. Maybe some notification from the bottom for first-time users, giving them the hint to press three times Escape in the row?

**Comment by cookiengineer** [comment]
Also, I just verified it: All icons in the UI bars have alt texts, so `:hover` is automatically showing the information about what the button or UI element does. This is the case for all UI widgets, including the Browser's internal pages and settings.

@2075 Please clarify?

**Comment by cookiengineer** [comment]
Closed due to inactivity and lack of clarification by @2075 .
