### ISSUE TITLE
Stealth (MacOS): Settings for a domain do not seem to land in the Stealth prefs

### ISSUE THREAD

**Issue by 2075** [cookiengineer/stealth-browser#25]
When setting preferences on macOS, reloading the whole page (session?) results in your previous settings being reset.

**Comment by cookiengineer** [comment]
Did you use the default stealth profile folder or use a custom `--profile=<path>` folder?

Can you check the Settings in `/Users/$USER/Library/Application Support/Stealth`? There should be a couple of JSON files that should look similar to this:

```bash
drwxr-xr-x  4 cookiengineer cookiengineer     4096 Jan  8 19:26 .
drwx------ 44 cookiengineer cookiengineer     4096 Mar  5 12:08 ..
-rw-r--r--  1 cookiengineer cookiengineer 17348789 Jan  8 15:46 blockers.json
drwxr-xr-x  4 cookiengineer cookiengineer     4096 Jan  8 15:46 cache
-rw-r--r--  1 cookiengineer cookiengineer        2 Mar  5 11:03 filters.json
-rw-r--r--  1 cookiengineer cookiengineer     1304 Mar  5 11:03 hosts.json
-rw-r--r--  1 cookiengineer cookiengineer       82 Mar  5 11:03 internet.json
-rw-r--r--  1 cookiengineer cookiengineer      147 Mar  5 11:03 modes.json
-rw-r--r--  1 cookiengineer cookiengineer        2 Mar  5 11:03 peers.json
-rw-r--r--  1 cookiengineer cookiengineer        2 Mar  5 11:03 redirects.json
-rw-r--r--  1 cookiengineer cookiengineer   163471 Mar  5 11:03 sessions.json
drwxr-xr-x  4 cookiengineer cookiengineer     4096 Jan  8 15:46 stash
```

**Comment by cookiengineer** [comment]
As of https://github.com/cookiengineer/stealth/commit/e49eabfa1a3bebe462e28ee4248b594b90f55459 the Settings Service and all data structures have end-to-end Reviews that work correctly as intended on Windows, MacOS, GNU/Linux, FreeBSD and OpenBSD as well as on Android.

@2075 If this behaviour happens again, please reopen and clarify.

In case it's still broken, please validate yourself that on your `host machine` these reviews work correctly:

```bash
cd /path/to/stealth-repository;

node covert/make.mjs;
node covert/covert.mjs scan stealth/client/Settings stealth/server/Settings;
```
