### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by hissssst** [cookiengineer/stealth-browser#43]
## Description

Application crashes on startup ocassionally

## Desired behaviour

No crashes please

## Actual behaviour

Sometimes crashes

## Steps to reproduce

Clone repo
Follow quickstart guide

## Enviroment

```
ChromeDriver 83.0.4103.116 (8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716})
Window manager: wayland sway version 1.5
```

**Comment by cookiengineer** [comment]
I need more input on this in order to figure out what's wrong.

1. Did you use the correct startup procedure?

```bash
cd /path/to/repo/of/stealth;

# make sure you are on the current development branch
git checkout X0;
git pull https://github.com/tholian-network/stealth.git X0;

# rebuild everything
node stealth/make.mjs clean;
node stealth/make.mjs build;

# startup in debug mode
node stealth/stealth.mjs --debug=true;
```

2. What were the errors you were experiencing?

3. In which Browser Engine? Did you use `browser/browser.mjs` or did you use another preinstalled Browser?

**Comment by hissssst** [comment]
Sorry for this issue. I've found out that it was `ungoogled-chromium-ozone`'s issue.
Closing
