### ISSUE TITLE
Browser: UI/UX Refactor

### ISSUE THREAD

**Issue by cookiengineer** [cookiengineer/stealth-browser#44]
The Browser UI Refactor that started with https://github.com/tholian-network/stealth/commit/40e9efc3348381c1985a92fbea5a5eaec1faedfb has the ultimate goal to have Widgets that can be instanciated on a per-data structure basis. Each Widget represents the complete data structure via their `this.model={}` property, whereas values and writable states are tracked in the `update` event of the Widget's element.

The goal behind this is to have no shitty shared-across-iframe-helpers that polluted the global scope and made interaction between the iframe and the window's parent a nightmare.

- [x] Implement `browser/design/card/Host` 
- [x] Implement `browser/design/card/Mode`  
- [x] Implement `browser/design/card/Beacon`
- [x] Implement `browser/design/card/Peer`
- [x] Implement `browser/design/card/Redirect`
- [x] Implement `browser/design/card/Session`
- [x] Implement `browser/design/card/Tab`
- [x] Implement `browser/design/card/Settings`

- [x] Reimplement `stealth:welcome` Page
- [x] Reimplement `stealth:fix-host` Page
- [x] Reimplement `stealth:fix-mode` Page
- [x] Reimplement `stealth:settings` Page

**Comment by cookiengineer** [comment]
As the Session turned out to be more complex, another `Tab` card is necessary in order to implement it cleanly.

The idea behind the `Tab` card is that it can be reused for the `stealth:history` page, which is just a `Session.query()` call to the current hostname in the `domain` field.

**Comment by 2075** [comment]
can i help with the ux?

**Comment by cookiengineer** [comment]
@2075 Sure! Currently most of the UX parts and workflows are actually kind of unplanned and a bit disorganized when it comes to the Internal Pages; and the Sidebars are still completely missing.

What parts would you like to work on?

**Comment by 2075** [comment]
proper ux makes only sense end to end. therefore a good starting point could be a simple tree with views and taking it from there. outcomes would be wireframes and maybe something like a styling for the application(s).

**Comment by 2075** [comment]
any updates on that?

**Comment by cookiengineer** [comment]
For me it's currently unclear what needs to be done for you to be able to work on this?

The current state of the project reflects the basic UX/UI ideas and tries to go from there in order to reach an MVP as soon as possible. But regarding UX, there are no plans, and no wireframes. So in order to know what you need, I would require something like a list of requirements.
